modLoader="javafml" #mandatory
loaderVersion="[38,)"
license="LGPLv3"

[[mods]] #mandatory
modId="unearthed" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Unearthed" #mandatory
logoFile="logo.png" #optional

credits="Corgi Taco & Aocawol for the original mod" #optional
authors="lilypuree" #optional
description='''
A mod that makes exploring underground interesting. Adds 21 new rocks!
'''

[[dependencies.unearthed]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.unearthed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.unearthed]]
    modId="hyle"
    mandatory=true
    versionRange="[0.1,)"
    ordering="AFTER"
    side="BOTH"
